### ISSUE TITLE
Docker-compose version '3.3' - volume_from not supported

### ISSUE THREAD

**Issue by Chabane** [smizy/docker-hbase#2]
Hello @smizy,

Thanks for sharing!

The `volume_from` is not supported in docker-compose 3.x version. 

I tried to replace `volume_from` : 

```
 namenode-1:
    container_name: namenode-1
    networks: ["vnet"]
    hostname: namenode-1.vnet
    image: smizy/hadoop-base:2.7.3-alpine
    expose: ["8020"]
    ports:  ["50070"]
    environment:
      - SERVICE_8020_NAME=namenode
      - SERVICE_50070_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181 
      - HADOOP_HEAPSIZE=1000
      - HADOOP_NAMENODE_HA=    
    entrypoint: entrypoint.sh
    volumes:
      - namenode:/usr/local/hadoop-2.7.3
    command: namenode-1

hmaster-1:
    container_name: hmaster-1
    networks: ["vnet"]
    hostname: hmaster-1.vnet
    image: smizy/hbase:1.2.6-alpine
    expose: [16000]
    ports:  [16010]
    depends_on: ["zookeeper-1"]
    environment:
      - SERVICE_16000_NAME=hmaster
      - SERVICE_16010_IGNORE=true
      - HBASE_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181   
    volumes:
      - namenode:/usr/local/hadoop-2.7.3
    command: hmaster-1
volumes:
  namenode:
```

And I got this error : 

```
namenode-1        | ls: /usr/local/hadoop-2.7.3/etc/hadoop/*.mustache: No such file or directory
namenode-1        | su-exec: hdfs: No such file or directory
```

Do you have any idea?

Thanks!
